[[[0,"/usr/lib/python3/dist-packages/service_identity/__init__.py","","",null,1],[false,[["CertificateError",true,2,["CertificateError",[0,"/usr/lib/python3/dist-packages/service_identity/exceptions.py","","",null,1],5]],["SubjectAltNameWarning",true,2,["SubjectAltNameWarning",[0,"/usr/lib/python3/dist-packages/service_identity/exceptions.py","","",null,1],5]],["VerificationError",true,2,["VerificationError",[0,"/usr/lib/python3/dist-packages/service_identity/exceptions.py","","",null,1],5]]]]]]